spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  sendgrid:
    api-key: ${SENDGRID_API_KEY:DUMMY-SENDGRID_API_KEY}
    from-email: quan93909@gmail.com
    templateId: d-8d276ce816254b399ebcc962d2f2199a
    verificationLink: http://localhost:8080/user/confirm-email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:8080
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: abc@123
  expiryMinutes: 5
  expiryDay: 14
  accessKey: IIwLeRIVsznVTPFEYmA6HiVVBrLKKkqC36OpWzqw8mk=
  refreshKey: tvszknimPZQEDy3c9TCERBLAk0yoCc2ZV0mGcHsRJgg=